### ISSUE TITLE
A CLI like NPM

### ISSUE THREAD

**Issue by mcwhittemore** [jaws-stack/JAWS-cli#10]
One of the things that I really like about the NPM module is that it is both the cli and a standard node module. This way you can build tools on top of the module and know it is going to work like npm.

I've started to break cli out in this same way but wanted to get some feedback before I went too far down this route.

https://github.com/mcwhittemore/JAWS-cli/tree/node-module-and-bin

**Comment by ac360** [comment]
@mcwhittemore I'm seriously loving your PRs.  I emailed you a link to the JAWS v1 spec.  We're discussing lots of CLI stuff in there.  In particular, is the difficult subject of deployment.  I want to make sure you're aware of the v1 spec because you are doing such great cli work.  

As soon as we can decide on the scope of work for JAWS v1, I will start digging into these PRs and merging the good stuff.  Please provide input on the JAWS v1 spec.  That's where we currently need the most help.  Plus, I want to make sure you stay informed so that when we open up a JAWS v1.0.0 branch (and probably a jaws-cli v1.0.0 branch) we can quickly build it.
